server:
  port: 8081
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        cluster-name: wuhan
      config:
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  application:
    name: producer
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 1
    host: 127.0.0.1